const ADMIN_USER='OVD-Flohmarkt',ADMIN_SALT='38913a46c7b925915a9ecf32ec7a32ad',ADMIN_HASH='16fac0afb939ef8264626a02dfe5de5bba1b2902745b3bfff5f3139ae931ff15';
const CATEGORIES=['Kleidung (Damen)','Kleidung (Herren)','Kleidung (Kinder 0-5 Jahre)','Kleidung (Kinder 6-11 Jahre)','Kleidung (Teens 12-18 Jahre)','Spielsachen / Bücher (Kinder 0-5 Jahre)','Spielsachen / Bücher (Kinder 6-11 Jahre)','Spielsachen / Bücher (Teens 12-18 Jahre)','Spiele / Bücher (Erwachsene)','Musik / Filme / Medien (CD, DVD, Schallplatten,...)','Elektronik Kleingeräte','Elektronik Großgeräte','Fahrräder, Roller, Dreiräder, etc. (Kinder 0-5 Jahre)','Fahrräder, Roller, etc. (Kinder 6-11 Jahre)','Fahrräder, Roller, etc. (Teens 12-18 Jahre)','Fahrräder, Roller, etc. (Erwachsene)','Haushaltswaren','Möbel','Antiquitäten / Sammlerobjekte','Gartenbedarf'];
const readStored=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch{return fallback}};
const writeStored=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
const state={data:null,loadError:'',mode:'all',favorites:new Set(readStored('du-favorites',[])),onlyFavorites:false,markers:new Map(),coords:readStored('du-coords',{}),map:null,routeMode:false,deleteMode:false,deleteSelected:new Set(),geoBusy:false,adminAuth:false};
const $=s=>document.querySelector(s),list=$('#list'),category=$('#category');
const norm=s=>(s||'').toLocaleLowerCase('de').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const safe=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isFood=p=>p.type==='food'||p.type==='both',isStand=p=>p.type==='stand'||p.type==='both';
const offerText=p=>[p.standOffers.length?'Angebot: '+p.standOffers.join(' · '):'',p.foodOffers.length?'Verpflegung: '+p.foodOffers.join(' · '):''].filter(Boolean).join(' | ');
function routeUrl(places){const ds=places.map(p=>encodeURIComponent(p.address+', Dudenhofen'));const dest=ds.pop();let u='https://www.google.com/maps/dir/?api=1&destination='+dest+'&travelmode=walking';if(ds.length)u+='&waypoints='+ds.join('%7C');return u}
function mapIcon(p){return L.divIcon({className:'',html:`<div class="pin ${isFood(p)?'food':'stand'} ${state.favorites.has(p.id)?'favorite':''} ${state.deleteSelected.has(p.id)?'delete-selected':''}"><span><img src="marker.png" alt="" width="25" height="25" style="display:block;border-radius:50%;transform:rotate(45deg)"></span></div>`,iconSize:[34,42],iconAnchor:[17,41],popupAnchor:[0,-38]})}
function placeLabel(p){return p.address.split(',')[0].trim()}
function placeKind(p){return isStand(p)&&isFood(p)?'Stand & Verpflegung':isFood(p)?'Verpflegung':'Flohmarktstand'}
function markerPopup(p){return `<b>${safe(placeLabel(p))}</b><br><small>${safe(placeKind(p))}</small><br>${safe(offerText(p))}`}
function updateMarker(p){if(!state.map||!state.coords[p.id])return;let m=state.markers.get(p.id);if(m){m.setIcon(mapIcon(p));m.setPopupContent(markerPopup(p));return}m=L.marker(state.coords[p.id],{icon:mapIcon(p)}).addTo(state.map).bindPopup(markerPopup(p));m.on('click',()=>{if(!state.deleteMode||!isStand(p))return;state.deleteSelected.has(p.id)?state.deleteSelected.delete(p.id):state.deleteSelected.add(p.id);m.closePopup();m.setIcon(mapIcon(p));$('#deleteSelectionCount').textContent=`${state.deleteSelected.size} ausgewählt`});state.markers.set(p.id,m)}
function categories(){for(const x of [...CATEGORIES,'Verpflegung']){const o=document.createElement('option');o.value=x;o.textContent=x;category.appendChild(o)}}
function normalizedAddress(s){return norm(s).replace(/\s+/g,' ').trim()}
function applyAdminEntry(entry){const gone=new Set([...readStored('du-deleted-ids',[]),...readStored('du-stand-deleted-ids',[])]);if(gone.has(entry.id)||entry.targetId&&gone.has(entry.targetId))return null;let target=entry.targetId?state.data.places.find(p=>p.id===entry.targetId):null;if(!target)target=state.data.places.find(p=>normalizedAddress(p.address)===normalizedAddress(entry.address));if(target){target.standOffers=[...new Set([...(target.standOffers||[]),...(entry.standOffers||[])])];target.categories=[...new Set([...(target.categories||[]),...(entry.categories||[]).filter(c=>CATEGORIES.includes(c))])];if(entry.type==='food'||entry.type==='both')target.type='both';return target}entry.categories=(entry.categories||[]).filter(c=>CATEGORIES.includes(c));state.data.places.push(entry);return entry}
function renderAdminCategories(){if(!state.data)return;const holder=$('#adminCategories');holder.innerHTML='';for(const value of CATEGORIES){const label=document.createElement('label');label.innerHTML=`<input type="checkbox" value="${safe(value)}"> <span>${safe(value)}</span>`;holder.appendChild(label)}}
function renderAdminEntries(){const entries=readStored('du-admin-entries',[]);$('#adminAddedCount').textContent=entries.length;$('#adminEntries').innerHTML=entries.length?[...entries].reverse().slice(0,8).map(e=>`<div class="admin-entry"><b>${safe(placeLabel(e))}</b><span>${safe(e.standOffers.join(' · '))}</span></div>`).join(''):'<div class="admin-empty">Noch keine lokalen Ergänzungen.</div>'}
function renderAdminErrors(){const holder=$('#adminErrors');if(state.loadError){holder.innerHTML=`<div class="admin-error"><b>Standortdaten nicht geladen</b><p>${safe(state.loadError)}</p></div>`;return}if(!state.data){holder.innerHTML='<div class="admin-empty">Datenprüfung noch nicht verfügbar.</div>';return}const missing=state.data.places.filter(p=>!state.coords[p.id]&&!p.coordinates);const mapIssue=!window.L?'<div class="admin-error"><b>Kartenbibliothek nicht geladen</b><p>Die Karte benötigt eine Internetverbindung. Prüfe den Zugriff auf unpkg.com.</p></div>':'';holder.innerHTML=mapIssue+(missing.length?`<p><b>${missing.length}</b> Standort${missing.length===1?'':'e'} ohne Kartenkoordinaten</p>`+missing.map(p=>`<form class="admin-error coord-form" data-coord-form="${safe(p.id)}"><b>${safe(placeLabel(p))}</b><label>Breitengrad<input name="lat" type="number" step="any" required placeholder="z. B. 49.32"></label><label>Längengrad<input name="lon" type="number" step="any" required placeholder="z. B. 8.39"></label><button class="btn" type="submit">Koordinaten speichern</button></form>`).join(''):'<div class="admin-empty">Keine Datenfehler gefunden. Alle Standorte haben Koordinaten.</div>')}
async function verifyAdminPassword(password){const encoder=new TextEncoder(),raw=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']),salt=new Uint8Array(ADMIN_SALT.match(/.{2}/g).map(x=>parseInt(x,16))),bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},raw,256),hash=[...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,'0')).join('');return hash===ADMIN_HASH}
function setView(view){if(view==='admin'&&!state.adminAuth)view='login';const admin=view==='admin',login=view==='login';$('#userArea').hidden=admin||login;$('#adminArea').hidden=!admin;$('#loginArea').hidden=!login;$('#adminOpen').classList.toggle('active',admin||login);$('#userOpen').classList.toggle('active',!admin&&!login);if(admin){$('#adminOpen').setAttribute('aria-current','page');$('#userOpen').removeAttribute('aria-current');renderAdminCategories();renderAdminEntries();renderAdminErrors()}else if(login){$('#adminOpen').setAttribute('aria-current','page');$('#userOpen').removeAttribute('aria-current');$('#loginError').textContent='';$('#loginUsername').focus()}else{$('#userOpen').setAttribute('aria-current','page');$('#adminOpen').removeAttribute('aria-current');if(state.map)requestAnimationFrame(()=>state.map.invalidateSize())}}
function exportData(){const entries=[['data.json',JSON.stringify(state.data,null,2)+'\n','application/json'],['data.js','window.MARKET_DATA = '+JSON.stringify(state.data)+';\n','text/javascript']];for(const [name,content,type] of entries){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('#adminMessage').textContent='data.json und data.js wurden heruntergeladen. Für die Veröffentlichung data.json ersetzen; für file:// auch data.js aktualisieren.'}
function visiblePlaces(){const q=norm($('#search').value),cat=category.value;let xs=state.data.places.filter(p=>{if(state.mode==='stand'&&!isStand(p)||state.mode==='food'&&!isFood(p))return false;if(state.onlyFavorites&&!state.favorites.has(p.id))return false;if($('#onlyFood').checked&&!isFood(p))return false;if(cat&&!p.categories.includes(cat))return false;if(q&&!norm(p.address+' '+offerText(p)+' '+p.categories.join(' ')).includes(q))return false;return true});const order=$('#sort').value;if(order==='type')xs.sort((a,b)=>Number(isFood(a))-Number(isFood(b))||a.address.localeCompare(b.address,'de'));else if(order==='favorite')xs.sort((a,b)=>Number(state.favorites.has(b.id))-Number(state.favorites.has(a.id))||a.address.localeCompare(b.address,'de'));else xs.sort((a,b)=>a.address.localeCompare(b.address,'de'));return xs}
function draw(){if(!state.data)return;const xs=visiblePlaces();$('#count').textContent=`${xs.length} ${xs.length===1?'Ort':'Orte'}`;list.innerHTML=xs.map(p=>`<article class="card" data-id="${safe(p.id)}"><div class="card-top"><div><h2>${safe(placeLabel(p))}</h2><div class="address">${isStand(p)?'🛍️ Stand':''}${isStand(p)&&isFood(p)?' · ':''}${isFood(p)?'🥨 Verpflegung':''}</div></div><button class="icon-btn ${state.favorites.has(p.id)?'saved':''}" data-fav="${safe(p.id)}" title="Favorit">${state.favorites.has(p.id)?'★':'☆'}</button></div><p class="offer">${safe(offerText(p)||'Angebot folgt')}</p><div class="chips">${p.categories.map(c=>`<span class="chip ${c==='Verpflegung'?'food':''}">${safe(c)}</span>`).join('')}</div><div class="card-actions"><button data-show="${safe(p.id)}">Auf Karte zeigen</button><a target="_blank" rel="noopener" href="${routeUrl([p])}">Route hierher ↗</a></div></article>`).join('')||'<div class="empty">Keine Treffer. Suche oder Filter anpassen.</div>';for(const [id,m] of state.markers)m.setOpacity(xs.some(p=>p.id===id)?1:.28)}
function focusPlace(id){const p=state.data.places.find(x=>x.id===id);if(!p)return;const m=state.markers.get(id);if(m){state.map.setView(m.getLatLng(),17);m.openPopup()}}
function saved(){writeStored('du-favorites',[...state.favorites]);draw();for(const p of state.data.places)if(state.coords[p.id])updateMarker(p)}
function initMap(){if(!window.L)return;state.map=L.map('map').setView([49.321,8.389],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap-Mitwirkende</a>'}).addTo(state.map);for(const p of state.data.places)updateMarker(p);const ll=Object.values(state.coords).filter(c=>Array.isArray(c));if(ll.length)state.map.fitBounds(ll,{padding:[30,30],maxZoom:16})}
function routeAction(){const box=$('#routebox');if(!state.routeMode){state.routeMode=true;box.classList.add('visible');$('#routeChoice').innerHTML=state.data.places.map(p=>`<option value="${safe(p.id)}">${isStand(p)?'🛍️':''}${isStand(p)&&isFood(p)?' + ':''}${isFood(p)?'🥨':''} ${safe(p.address)}</option>`).join('');$('#route').textContent='Route in Karten öffnen';return}const chosen=[...$('#routeChoice').selectedOptions].map(o=>state.data.places.find(p=>p.id===o.value)).filter(Boolean);if(!chosen.length){alert('Bitte mindestens einen Halt auswählen.');return}window.open(routeUrl(chosen),'_blank','noopener')}
function parseCsv(text){const first=text.split(/\r?\n/,1)[0]||'',delimiter=(first.match(/;/g)||[]).length>=(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')quoted=!quoted;else if(ch===delimiter&&!quoted){row.push(cell.trim());cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}
async function importStandCsv(){const file=$('#standImportFile').files[0];if(!file){$('#importMessage').textContent='Bitte zuerst eine CSV-Datei auswählen.';return}try{const rows=parseCsv((await file.text()).replace(/^\uFEFF/,''));if(!rows.length)throw Error('Die Datei ist leer.');let start=0,ai=0,ci=1,oi=2;const headers=rows[0].map(norm);if(headers.some(h=>h.includes('adresse')||h.includes('strasse')||h.includes('address'))){start=1;ai=headers.findIndex(h=>h.includes('adresse')||h.includes('strasse')||h.includes('address'));ci=headers.findIndex(h=>h.includes('kategorie')||h.includes('category'));oi=headers.findIndex(h=>h.includes('angebot')||h.includes('offer'))}let added=0,skipped=0;const entries=readStored('du-admin-entries',[]);for(const row of rows.slice(start)){const address=(row[ai]||'').trim();if(!address){skipped++;continue}const rawCats=ci>=0?(row[ci]||''):'';const cats=[...new Set(rawCats.split('|').map(c=>c.trim()).filter(c=>CATEGORIES.includes(c)))];if(!cats.length){skipped++;continue}const offer=oi>=0?(row[oi]||'').trim():'';const fullAddress=/67373\s+Dudenhofen/i.test(address)?address:`${address}, 67373 Dudenhofen`;const existing=state.data?.places.find(p=>normalizedAddress(p.address)===normalizedAddress(fullAddress));const entry={id:existing?.id||'import-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),targetId:existing?.id||null,type:'stand',address:fullAddress,standOffers:[offer||cats.join(' · ')],foodOffers:[],categories:cats,coordinates:null,adminCreated:true,incomplete:false};entries.push(entry);if(state.data)applyAdminEntry(entry);added++}if(added){writeStored('du-admin-entries',entries);draw();renderAdminEntries();renderAdminErrors()}$('#importMessage').textContent=`${added} Stand${added===1?'':'stände'} importiert; ${skipped} Zeile${skipped===1?'':'n'} übersprungen (Adresse oder passende Kategorie fehlt). Bitte Daten exportieren, um sie zu veröffentlichen.`}catch(err){$('#importMessage').textContent='CSV konnte nicht gelesen werden. Erwartet wird Adresse;Kategorien;Angebot.'}}
function cancelDeleteMode(){state.deleteMode=false;state.deleteSelected.clear();$('#deleteMapTools').hidden=true;for(const p of state.data?.places||[])updateMarker(p)}
function removeSelectedStands(){const ids=[...state.deleteSelected];if(!ids.length){$('#deleteSelectionCount').textContent='Bitte Marker auswählen';return}if(!confirm(`${ids.length} ausgewählte${ids.length===1?'r Standort':' Standorte'} löschen? Diese Änderung betrifft die Daten auf diesem Gerät.`))return;const fullDeleted=new Set(readStored('du-deleted-ids',[])),standDeleted=new Set(readStored('du-stand-deleted-ids',[]));for(const id of ids){const p=state.data.places.find(x=>x.id===id);if(!p)continue;if(isFood(p)&&isStand(p)){p.standOffers=[];p.categories=(p.categories||[]).filter(c=>c==='Verpflegung');p.type='food';standDeleted.add(id);updateMarker(p)}else{fullDeleted.add(id);state.data.places=state.data.places.filter(x=>x.id!==id);const marker=state.markers.get(id);if(marker)marker.remove();state.markers.delete(id)}state.coords[id]&&writeStored('du-coords',state.coords)}writeStored('du-deleted-ids',[...fullDeleted]);writeStored('du-stand-deleted-ids',[...standDeleted]);const remaining=readStored('du-admin-entries',[]).filter(e=>!ids.includes(e.id)&&!ids.includes(e.targetId));writeStored('du-admin-entries',remaining);cancelDeleteMode();draw();renderAdminEntries();renderAdminErrors();$('#importMessage').textContent=`${ids.length} Standort${ids.length===1?'':'e'} entfernt. Über „Daten exportieren“ dauerhaft veröffentlichen.`;setView('admin')}
const appData=location.protocol==='file:'&&window.MARKET_DATA?Promise.resolve(window.MARKET_DATA):fetch('data.json').then(r=>{if(!r.ok)throw new Error('data.json nicht verfügbar');return r.json()});
appData.then(data=>{const deleted=new Set(readStored('du-deleted-ids',[])),standDeleted=new Set(readStored('du-stand-deleted-ids',[]));data.places=data.places.filter(p=>!deleted.has(p.id));state.data=data;for(const p of data.places){if(state.coords[p.id])p.coordinates=state.coords[p.id];else if(p.coordinates)state.coords[p.id]=p.coordinates}for(const entry of readStored('du-admin-entries',[]))applyAdminEntry(entry);for(const p of data.places)if(standDeleted.has(p.id)){p.standOffers=[];p.categories=(p.categories||[]).filter(c=>c==='Verpflegung');if(p.type==='both')p.type='food'}categories();initMap();draw()}).catch(()=>{state.loadError='Die data.json konnte nicht geladen werden. Prüfe, ob sie neben der App liegt und lesbar ist.';$('#count').textContent=''});
document.addEventListener('click',e=>{const fav=e.target.closest('[data-fav]');if(fav){const id=fav.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saved();return}const show=e.target.closest('[data-show]');if(show)focusPlace(show.dataset.show)});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));state.mode=b.dataset.mode;draw()}));
$('#search').addEventListener('input',draw);category.addEventListener('change',draw);$('#sort').addEventListener('change',draw);$('#onlyFood').addEventListener('change',draw);$('#favorites').addEventListener('click',e=>{state.onlyFavorites=!state.onlyFavorites;e.currentTarget.classList.toggle('primary',state.onlyFavorites);e.currentTarget.textContent=state.onlyFavorites?'★ Favoriten':'☆ Favoriten';draw()});$('#route').addEventListener('click',routeAction);$('#mapList').addEventListener('click',()=>$('#mapStatus').classList.add('hide-mobile'));
$('#importStands').addEventListener('click',importStandCsv);$('#startDeleteMode').addEventListener('click',()=>{if(!state.map){$('#importMessage').textContent='Die Karte ist nicht verfügbar; Löschen über die Karte ist derzeit nicht möglich.';return}state.deleteMode=true;state.deleteSelected.clear();$('#deleteSelectionCount').textContent='0 ausgewählt';$('#deleteMapTools').hidden=false;setView('user');requestAnimationFrame(()=>state.map.invalidateSize())});$('#cancelDeleteMode').addEventListener('click',cancelDeleteMode);$('#deleteSelected').addEventListener('click',removeSelectedStands);
$('#adminErrors').addEventListener('submit',e=>{const form=e.target.closest('[data-coord-form]');if(!form)return;e.preventDefault();const lat=Number(form.elements.lat.value),lon=Number(form.elements.lon.value);if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat < -90||lat > 90||lon < -180||lon > 180){alert('Bitte gültige Breiten- und Längengrade eingeben.');return}const p=state.data.places.find(x=>x.id===form.dataset.coordForm);if(!p)return;state.coords[p.id]=[lat,lon];p.coordinates=[lat,lon];writeStored('du-coords',state.coords);updateMarker(p);if(state.map)state.map.fitBounds(Object.values(state.coords).filter(Array.isArray),{padding:[30,30],maxZoom:16});renderAdminErrors();draw()});
$('#adminOpen').addEventListener('click',()=>setView('admin'));$('#userOpen').addEventListener('click',()=>setView('user'));$('#userBack').addEventListener('click',()=>setView('user'));$('#adminLogout').addEventListener('click',()=>{state.adminAuth=false;$('#loginPassword').value='';setView('user')});$('#loginBack').addEventListener('click',()=>setView('user'));$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{const ok=$('#loginUsername').value===ADMIN_USER&&await verifyAdminPassword($('#loginPassword').value);$('#loginPassword').value='';if(ok){state.adminAuth=true;$('#loginForm').reset();setView('admin')}else $('#loginError').textContent='Benutzername oder Passwort ist nicht korrekt.'}catch{$('#loginError').textContent='Die Loginprüfung ist in diesem Browser nicht verfügbar. Bitte öffne die App über HTTPS.'}});$('#adminForm').addEventListener('submit',e=>{e.preventDefault();let address=$('#newAddress').value.trim().replace(/\s+/g,' ');if(!/67373\s+Dudenhofen/i.test(address))address+=', 67373 Dudenhofen';const offer=$('#newOffer').value.trim();const cats=[...$('#adminCategories').querySelectorAll('input:checked')].map(i=>i.value);if(!cats.length){$('#adminMessage').textContent='Bitte mindestens eine Kategorie auswählen.';return}const existing=state.data.places.find(p=>normalizedAddress(p.address)===normalizedAddress(address));const entry={id:existing?existing.id:'admin-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),targetId:existing?.id||null,type:'stand',address,standOffers:[offer],foodOffers:[],categories:[...new Set(cats)],coordinates:null,adminCreated:true,incomplete:false};const savedEntries=readStored('du-admin-entries',[]);savedEntries.push(entry);const persisted=writeStored('du-admin-entries',savedEntries);const updated=applyAdminEntry(entry);draw();if(updated.coordinates)updateMarker(updated);renderAdminCategories();renderAdminEntries();renderAdminErrors();$('#adminMessage').textContent=persisted?'Stand gespeichert. Für alle Besucher: „Daten exportieren“.':'Stand für diese Sitzung angelegt. Bitte jetzt exportieren, damit der Eintrag nicht verloren geht.';$('#adminForm').reset()});$('#exportData').addEventListener('click',exportData);
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
