const readStored=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch{return fallback}};
const writeStored=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const state={data:null,mode:'all',favorites:new Set(readStored('du-favorites',[])),onlyFavorites:false,markers:new Map(),coords:readStored('du-coords',{}),map:null,routeMode:false,geoBusy:false};
const $=s=>document.querySelector(s),list=$('#list'),category=$('#category');
const norm=s=>(s||'').toLocaleLowerCase('de').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const safe=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isFood=p=>p.type==='food'||p.type==='both',isStand=p=>p.type==='stand'||p.type==='both';
const offerText=p=>[p.standOffers.length?'Angebot: '+p.standOffers.join(' · '):'',p.foodOffers.length?'Verpflegung: '+p.foodOffers.join(' · '):''].filter(Boolean).join(' | ');
function routeUrl(places){const ds=places.map(p=>encodeURIComponent(p.address+', Dudenhofen'));const dest=ds.pop();let u='https://www.google.com/maps/dir/?api=1&destination='+dest+'&travelmode=walking';if(ds.length)u+='&waypoints='+ds.join('%7C');return u}
function mapIcon(p){return L.divIcon({className:'',html:`<div class="pin ${isFood(p)?'food':'stand'} ${state.favorites.has(p.id)?'favorite':''}"><span><img src="marker.png" alt="" width="25" height="25" style="display:block;border-radius:50%;transform:rotate(45deg)"></span></div>`,iconSize:[34,42],iconAnchor:[17,41],popupAnchor:[0,-38]})}
function markerPopup(p){const title=isStand(p)&&isFood(p)?'Stand & Verpflegung':isFood(p)?'Verpflegung':'Flohmarktstand';return `<b>${title}</b><br>${safe(p.address)}<br>${safe(offerText(p))}`}
function updateMarker(p){if(!state.map||!state.coords[p.id])return;let m=state.markers.get(p.id);if(m){m.setIcon(mapIcon(p));m.setPopupContent(markerPopup(p));return}m=L.marker(state.coords[p.id],{icon:mapIcon(p)}).addTo(state.map).bindPopup(markerPopup(p));state.markers.set(p.id,m)}
function categories(){const values=[...new Set(state.data.places.flatMap(p=>p.categories))].sort((a,b)=>a.localeCompare(b,'de'));for(const x of values){if([...category.options].some(o=>o.value===x))continue;const o=document.createElement('option');o.value=x;o.textContent=x;category.appendChild(o)}}
function normalizedAddress(s){return norm(s).replace(/\s+/g,' ').trim()}
function applyAdminEntry(entry){let target=entry.targetId?state.data.places.find(p=>p.id===entry.targetId):null;if(!target)target=state.data.places.find(p=>normalizedAddress(p.address)===normalizedAddress(entry.address));if(target){target.standOffers=[...new Set([...(target.standOffers||[]),...(entry.standOffers||[])])];target.categories=[...new Set([...(target.categories||[]),...(entry.categories||[])])];if(entry.type==='food'||entry.type==='both')target.type='both';return target}state.data.places.push(entry);return entry}
function renderAdminCategories(){const holder=$('#adminCategories');holder.innerHTML='';const values=[...new Set(state.data.places.flatMap(p=>p.categories).filter(c=>c!=='Verpflegung'))].sort((a,b)=>a.localeCompare(b,'de'));for(const value of values){const label=document.createElement('label');label.innerHTML=`<input type="checkbox" value="${safe(value)}"> <span>${safe(value)}</span>`;holder.appendChild(label)}}
function exportData(){const entries=[['data.json',JSON.stringify(state.data,null,2)+'\n','application/json'],['data.js','window.MARKET_DATA = '+JSON.stringify(state.data)+';\n','text/javascript']];for(const [name,content,type] of entries){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('#adminMessage').textContent='data.json und data.js wurden heruntergeladen. Für die Veröffentlichung data.json ersetzen; für file:// auch data.js aktualisieren.'}
function visiblePlaces(){const q=norm($('#search').value),cat=category.value;let xs=state.data.places.filter(p=>{if(state.mode==='stand'&&!isStand(p)||state.mode==='food'&&!isFood(p))return false;if(state.onlyFavorites&&!state.favorites.has(p.id))return false;if($('#onlyFood').checked&&!isFood(p))return false;if(cat&&!p.categories.includes(cat))return false;if(q&&!norm(p.address+' '+offerText(p)+' '+p.categories.join(' ')).includes(q))return false;return true});const order=$('#sort').value;if(order==='type')xs.sort((a,b)=>Number(isFood(a))-Number(isFood(b))||a.address.localeCompare(b.address,'de'));else if(order==='favorite')xs.sort((a,b)=>Number(state.favorites.has(b.id))-Number(state.favorites.has(a.id))||a.address.localeCompare(b.address,'de'));else xs.sort((a,b)=>a.address.localeCompare(b.address,'de'));return xs}
function draw(){if(!state.data)return;const xs=visiblePlaces();$('#count').textContent=`${xs.length} ${xs.length===1?'Ort':'Orte'}`;list.innerHTML=xs.map(p=>`<article class="card" data-id="${safe(p.id)}"><div class="card-top"><div><h2>${isStand(p)?'🛍️ Stand':''}${isStand(p)&&isFood(p)?' · ':''}${isFood(p)?'🥨 Verpflegung':''}</h2><div class="address">${safe(p.address)}</div></div><button class="icon-btn ${state.favorites.has(p.id)?'saved':''}" data-fav="${safe(p.id)}" title="Favorit">${state.favorites.has(p.id)?'★':'☆'}</button></div><p class="offer">${safe(offerText(p)||'Angebot folgt')}</p><div class="chips">${p.categories.map(c=>`<span class="chip ${c==='Verpflegung'?'food':''}">${safe(c)}</span>`).join('')}</div><div class="card-actions"><button data-show="${safe(p.id)}">Auf Karte zeigen</button><a target="_blank" rel="noopener" href="${routeUrl([p])}">Route hierher ↗</a></div></article>`).join('')||'<div class="empty">Keine Treffer. Suche oder Filter anpassen.</div>';for(const [id,m] of state.markers)m.setOpacity(xs.some(p=>p.id===id)?1:.28)}
function focusPlace(id){const p=state.data.places.find(x=>x.id===id);if(!p)return;const m=state.markers.get(id);if(m){state.map.setView(m.getLatLng(),17);m.openPopup()}else{$('#mapStatus').scrollIntoView({behavior:'smooth',block:'center'});$('#mapStatus').querySelector('strong').textContent='Standort noch nicht auf der Karte';}}
function saved(){writeStored('du-favorites',[...state.favorites]);draw();for(const p of state.data.places)if(state.coords[p.id])updateMarker(p)}
function initMap(){if(!window.L){$('#mapStatus strong').textContent='Karte braucht Internet';return}state.map=L.map('map').setView([49.321,8.389],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap-Mitwirkende</a>'}).addTo(state.map);for(const p of state.data.places)updateMarker(p);const ll=Object.values(state.coords).filter(c=>Array.isArray(c));if(ll.length)state.map.fitBounds(ll,{padding:[30,30],maxZoom:16})}
function routeAction(){const box=$('#routebox');if(!state.routeMode){state.routeMode=true;box.classList.add('visible');$('#routeChoice').innerHTML=state.data.places.map(p=>`<option value="${safe(p.id)}">${isStand(p)?'🛍️':''}${isStand(p)&&isFood(p)?' + ':''}${isFood(p)?'🥨':''} ${safe(p.address)}</option>`).join('');$('#route').textContent='Route in Karten öffnen';return}const chosen=[...$('#routeChoice').selectedOptions].map(o=>state.data.places.find(p=>p.id===o.value)).filter(Boolean);if(!chosen.length){alert('Bitte mindestens einen Halt auswählen.');return}window.open(routeUrl(chosen),'_blank','noopener')}
const appData=location.protocol==='file:'&&window.MARKET_DATA?Promise.resolve(window.MARKET_DATA):fetch('data.json').then(r=>{if(!r.ok)throw new Error('data.json nicht verfügbar');return r.json()});
appData.then(data=>{state.data=data;for(const entry of readStored('du-admin-entries',[]))applyAdminEntry(entry);for(const p of data.places)if(p.coordinates)state.coords[p.id]=p.coordinates;categories();initMap();draw();const located=data.places.filter(p=>p.coordinates).length;$('#mapStatus strong').textContent=`Karte: ${located} von ${data.places.length} Standorten verortet`}).catch(()=>{$('#count').textContent='Daten konnten nicht geladen werden'});
document.addEventListener('click',e=>{const fav=e.target.closest('[data-fav]');if(fav){const id=fav.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saved();return}const show=e.target.closest('[data-show]');if(show)focusPlace(show.dataset.show)});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));state.mode=b.dataset.mode;draw()}));
$('#search').addEventListener('input',draw);category.addEventListener('change',draw);$('#sort').addEventListener('change',draw);$('#onlyFood').addEventListener('change',draw);$('#favorites').addEventListener('click',e=>{state.onlyFavorites=!state.onlyFavorites;e.currentTarget.classList.toggle('primary',state.onlyFavorites);e.currentTarget.textContent=state.onlyFavorites?'★ Favoriten':'☆ Favoriten';draw()});$('#route').addEventListener('click',routeAction);$('#mapList').addEventListener('click',()=>$('#mapStatus').classList.add('hide-mobile'));
$('#adminOpen').addEventListener('click',()=>{renderAdminCategories();$('#adminMessage').textContent='';$('#adminDialog').showModal()});$('#adminClose').addEventListener('click',()=>$('#adminDialog').close());$('#adminForm').addEventListener('submit',e=>{e.preventDefault();let address=$('#newAddress').value.trim().replace(/\s+/g,' ');if(!/67373\s+Dudenhofen/i.test(address))address+=', 67373 Dudenhofen';const offer=$('#newOffer').value.trim();const cats=[...$('#adminCategories').querySelectorAll('input:checked')].map(i=>i.value);const extra=$('#newCategory').value.trim();if(extra)cats.push(extra);if(!cats.length)cats.push('Sonstiges');const existing=state.data.places.find(p=>normalizedAddress(p.address)===normalizedAddress(address));const entry={id:existing?existing.id:'admin-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),targetId:existing?.id||null,type:'stand',address,standOffers:[offer],foodOffers:[],categories:[...new Set(cats)],coordinates:null,adminCreated:true,incomplete:false};const savedEntries=readStored('du-admin-entries',[]);savedEntries.push(entry);writeStored('du-admin-entries',savedEntries);const updated=applyAdminEntry(entry);if(extra&&![...category.options].some(o=>o.value===extra)){const opt=document.createElement('option');opt.value=extra;opt.textContent=extra;category.appendChild(opt)}draw();if(updated.coordinates)updateMarker(updated);$('#adminMessage').textContent='Stand gespeichert. Für alle Besucher: „Daten exportieren“.';$('#adminForm').reset()});$('#exportData').addEventListener('click',exportData);
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
